[package]
name = "spotiferris"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
edition = "2018"

[dependencies]
gotham        = "0.4.0"
gotham_derive = "0.4.0"
serde         = { version = "1.0", features = ["derive"] }
hyper         = "0.12"
mime          = "0.3"
askama        = { version = "0.8" }
diesel        = { version = "1.4.3", features = ["postgres"] }
dotenv        = "0.10"
id3           = "0.3"
mp3-duration  = "0.1.7"
url           = "2.1.1"
futures       = "0.1"
