[package]
name = "spotiferris"
version = "0.1.0"
authors = ["Andrew Radev <andrey.radev@gmail.com>"]
edition = "2018"

[dependencies]
gotham = "*"
gotham_derive = "*"
serde = "*"
serde_derive = "*"
hyper = "*"
http = "*"
mime = "*"
askama = "*"

[build-dependencies]
askama = "*"
